"""
Mock data generator for demo mode.

Provides sample data when API key is not available.
"""

import json
from typing import Any, Dict, List

import logging

logger = logging.getLogger(__name__)


def get_mock_preferences(user_input: str) -> Dict[str, Any]:
    """
    Generate mock preferences based on user input.

    Args:
        user_input: User's natural language input.

    Returns:
        Mock preferences dictionary.
    """
    # Extract some keywords from user input for more realistic mock data
    user_lower = user_input.lower()
    
    interests = []
    if any(word in user_lower for word in ["museum", "art", "gallery"]):
        interests.append("Museums")
    if any(word in user_lower for word in ["beach", "ocean", "sea"]):
        interests.append("Beaches")
    if any(word in user_lower for word in ["food", "dining", "restaurant", "cuisine"]):
        interests.append("Food & Dining")
    if any(word in user_lower for word in ["history", "historic", "ancient"]):
        interests.append("History")
    if any(word in user_lower for word in ["nature", "hiking", "outdoor"]):
        interests.append("Nature")
    if not interests:
        interests = ["Museums", "Food & Dining", "History"]

    travel_style = None
    if any(word in user_lower for word in ["budget", "cheap", "affordable"]):
        travel_style = "Budget"
    elif any(word in user_lower for word in ["luxury", "premium", "high-end"]):
        travel_style = "Luxury"
    else:
        travel_style = "Mid-range"

    accommodation = None
    if any(word in user_lower for word in ["hotel"]):
        accommodation = "Hotel"
    elif any(word in user_lower for word in ["hostel"]):
        accommodation = "Hostel"
    elif any(word in user_lower for word in ["airbnb", "apartment"]):
        accommodation = "Airbnb"
    else:
        accommodation = "Hotel"

    dietary = []
    if any(word in user_lower for word in ["vegetarian", "vegan"]):
        dietary.append("Vegetarian")
    if any(word in user_lower for word in ["gluten", "celiac"]):
        dietary.append("Gluten-free")

    return {
        "interests": interests,
        "travel_style": travel_style,
        "accommodation_type": accommodation,
        "dietary_restrictions": dietary,
        "special_requirements": [],
        "additional_notes": "Demo mode - preferences extracted from keywords",
    }


def get_mock_recommendations(destination: str, preferences: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate mock recommendations for a destination.

    Args:
        destination: Travel destination.
        preferences: User preferences.

    Returns:
        Mock recommendations dictionary.
    """
    interests = preferences.get("interests", [])
    
    attractions = [
        f"Explore the historic city center of {destination}",
        "Visit local museums and art galleries",
        "Take a guided walking tour",
        "Experience local markets and shopping districts",
    ]
    
    if "Beaches" in interests:
        attractions.append("Relax at beautiful beaches")
    if "Nature" in interests:
        attractions.append("Hike scenic nature trails")

    accommodations = [
        f"Luxury hotels in downtown {destination}",
        "Boutique accommodations with local charm",
        "Budget-friendly hostels near city center",
    ]

    dining = [
        "Fine dining restaurants with local cuisine",
        "Street food markets for authentic flavors",
        "Cafes and bistros for casual dining",
    ]

    if preferences.get("dietary_restrictions"):
        dietary_list = ", ".join(preferences["dietary_restrictions"])
        dining.append(f"Restaurants accommodating {dietary_list}")

    transportation = [
        "Public transportation system (metro/bus)",
        "Taxi and ride-sharing services",
        "Walking and bike rentals",
    ]

    tips = [
        "Best time to visit: Spring or Fall for pleasant weather",
        "Learn a few basic phrases in the local language",
        "Carry cash for small vendors and markets",
        "Respect local customs and traditions",
    ]

    full_text = f"""
# Travel Recommendations for {destination}

## Top Attractions
{chr(10).join(f"- {attr}" for attr in attractions)}

## Accommodations
{chr(10).join(f"- {acc}" for acc in accommodations)}

## Dining
{chr(10).join(f"- {din}" for din in dining)}

## Transportation
{chr(10).join(f"- {trans}" for trans in transportation)}

## Tips & Advice
{chr(10).join(f"- {tip}" for tip in tips)}

*Note: This is demo/mock data. In production, recommendations would be generated by AI based on real-time information.*
    """.strip()

    return {
        "destination": destination,
        "attractions": attractions,
        "accommodations": accommodations,
        "dining": dining,
        "transportation": transportation,
        "tips": tips,
        "full_text": full_text,
    }


def get_mock_itinerary(
    destination: str, duration: int, preferences: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Generate mock itinerary for a destination.

    Args:
        destination: Travel destination.
        duration: Number of days.
        preferences: User preferences.

    Returns:
        List of day dictionaries.
    """
    itinerary = []
    interests = preferences.get("interests", [])

    for day in range(1, duration + 1):
        day_data = {
            "day": day,
            "date": None,
            "morning": [],
            "afternoon": [],
            "evening": [],
            "notes": [],
        }

        if day == 1:
            day_data["morning"] = [
                f"Arrive in {destination} and check into accommodation",
                "Get oriented with a city map and transportation pass",
            ]
            day_data["afternoon"] = [
                "Take a guided walking tour of the historic center",
                "Visit a local market to experience the culture",
            ]
            day_data["evening"] = [
                "Enjoy dinner at a local restaurant",
                "Take a leisurely evening stroll",
            ]
            day_data["notes"] = [
                "Take it easy on the first day to adjust to time zone",
            ]

        elif day == duration:
            day_data["morning"] = [
                "Visit any remaining must-see attractions",
                "Last-minute souvenir shopping",
            ]
            day_data["afternoon"] = [
                "Enjoy a final meal at a favorite restaurant",
                "Prepare for departure",
            ]
            day_data["evening"] = [
                "Departure or final evening in the city",
            ]
            day_data["notes"] = [
                "Check out time and airport transfer arrangements",
            ]

        else:
            if "Museums" in interests:
                day_data["morning"] = [
                    f"Visit museums and art galleries in {destination}",
                ]
            else:
                day_data["morning"] = [
                    f"Explore {destination}'s main attractions",
                ]

            if "Beaches" in interests:
                day_data["afternoon"] = [
                    "Relax at the beach or waterfront",
                    "Enjoy water activities",
                ]
            elif "Nature" in interests:
                day_data["afternoon"] = [
                    "Hike nature trails or visit parks",
                    "Enjoy outdoor activities",
                ]
            else:
                day_data["afternoon"] = [
                    "Continue exploring the city",
                    "Visit local neighborhoods",
                ]

            if "Food & Dining" in interests:
                day_data["evening"] = [
                    "Food tour or cooking class",
                    "Dinner at a recommended restaurant",
                ]
            else:
                day_data["evening"] = [
                    "Evening entertainment or nightlife",
                    "Dinner and relaxation",
                ]

            day_data["notes"] = [
                "Wear comfortable walking shoes",
                "Check opening hours for attractions",
            ]

        itinerary.append(day_data)

    return itinerary

